name: 'bigquery_edw'
version: '1.0.0'
config-version: 2
require-dbt-version: '>=1.3.0'

profile: 'bigquery-edw'

vars:
  disable_dbt_invocation_autoupload: "{{ target.name != 'prod' }}"
  freshness_hours_warn: '42' # Freshness check time period in hours
  freshness_hours_error: '70'
  query_max_size: 50000

# Configuring paths
model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_modules"

dispatch:
  - macro_namespace: datavault4dbt
    search_order: ['datavault4dbt', 'bigquery-edw']

#vars:
#  dbt_artifacts_database: scalefree-edw-dev
#  dbt_artifacts_schema: meta

models:
  bigquery_edw:
    .archive:
      +enabled: false
    stg_raw:
      +materialized: view
      # +schema: townhall3
      # +meta: 
      #   layer: townhall
    stg_dv:
      +materialized: view
    raw_vault:
      +materialized: table
      TOWNHALL_3:
        +materialized: incremental
        v0:
          +materialized: incremental
          +meta: 
            type: satellite
        v1:
          +materialized: view 
    business_vault:
      +materialized: incremental
      +schema: edw_core
      +meta: 
        layer: business-vault
    marts:
      +materialized: view
      +meta: 
        layer: information-delivery
    control:
      +materialized: incremental
      +schema: control
      +meta: 
        layer: control
  elementary:
    +schema: 'meta'

